apiVersion: v1
kind: Service
metadata:
  name: student-outcome-prediction-model-service
spec:
  type: LoadBalancer
  selector:
    app: student-outcome-prediction-modeltext
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501